### ISSUE TITLE
Andnroid libgaclient.so has text relocations

### ISSUE THREAD

**Issue by miaoshuncai** [chunying/gaminganywhere#91]
**when android api >=23, I have "text relocations" crash:**,
I tried add these config in Android.mk, but no used, please help me:
LOCAL_CFLAGS := -fPIC
the crash log is:
2020-11-09 09:30:28.692 14623-14623/org.gaminganywhere.gaclient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.gaminganywhere.gaclient, PID: 14623
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.gaminganywhere.gaclient-UMAuDqbmy40r9Q_L2BTwdA==/lib/arm/libgaclient.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.gaminganywhere.gaclient.GAClient.<clinit>(GAClient.java:727)
        at org.gaminganywhere.gaclient.PlayerActivity.connect(PlayerActivity.java:123)
        at org.gaminganywhere.gaclient.PlayerActivity.onResume(PlayerActivity.java:255)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:8050)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4260)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4302)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by dubeyabhijeet** [comment]
HI,

Can you share me config profile you created in app?
